name: Bug Report
description: Report a bug in the GENEVE Protocol Parser
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ License Notice
        This is proprietary software with restrictive licensing. Please review the [LICENSE](../LICENSE) file.
        
        ## Security Issues
        **Do NOT report security vulnerabilities here.** Follow our [Security Policy](../SECURITY.md).

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Process PCAP file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please complete the following information
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 14.0, Windows 11]
        - Go Version: [e.g. go1.21.0]
        - Parser Version: [e.g. v1.0.0]
        - Command: [exact command used]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Copy and paste relevant log output
      render: shell
    validations:
      required: false

  - type: textarea
    id: pcap
    attributes:
      label: PCAP Information
      description: |
        **Do NOT upload sensitive PCAP files.**
        Provide information about the PCAP if relevant:
        - File size
        - Number of GENEVE packets
        - Vendor types involved
        - Any special characteristics
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have read and understood the LICENSE file
          required: true
        - label: This is not a security vulnerability (use Security Policy for those)
          required: true
        - label: I have searched existing issues
          required: true
        - label: I have provided all requested information
          required: true